name: 'Start Android Emulator'
description: 'Installs and starts an Android Emulator'

inputs:
  script:
    description: 'The script to run'
    required: true

runs:
  using: "composite"
  steps:
    - uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        arch: x86
        target: aosp_atd
        profile: Nexus One
        disk-size: 2048M
        script: ${{ inputs.script }}
