name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: published

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
  ORG_GRADLE_PROJECT_reverseGeocodingKey: ${{ secrets.REVERSE_GEOCODING_KEY }}
  ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup host
        uses: ./.github/actions/setup-host
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Test & Build
        run: |
          ./gradlew build bootstrapListing
      - name: Publish Test Report
        if: ${{ !cancelled() }}
        uses: gmazzo/publish-report-annotations@v1
        with:
          checkName: Test Results
      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: '**/build/reports'
      - name: Coverage report
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: '**/build/reports/jacoco/**/*.xml'

  ui-tests:
    name: UI Tests
    if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'Skip UI Tests') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup host
        uses: ./.github/actions/setup-host
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_TESTLAB_CREDENTIALS }}
      - name: Run UI tests
        run: |
          ./gradlew firebaseTestLabCheck -Pminified=true
      - name: Publish Test Report
        if: ${{ !cancelled() }}
        uses: gmazzo/publish-report-annotations@v1
        with:
          checkName: Screenshot Tests Results
      - name: Archive test results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: '**/build/outputs/*-results/'

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ build, ui-tests ]
    if: ${{ !cancelled() && github.event_name == 'release' && !contains(needs.*.result, 'failure') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup host
        uses: ./.github/actions/setup-host
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Publish to Google Play
        run: |
          ./gradlew \
            publishReleaseBundle --track=internal \
            promoteArtifact --from-track=internal --promote-track=production

  actionlint:
    name: Validate Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Download actionlint
        shell: bash
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Check workflow files
        shell: bash
        run: ./actionlint -color -format '{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Message}}%0A```%0A{{replace $err.Snippet "\\n" "%0A"}}%0A```\n{{end}}' -ignore 'SC2016:'
