name: Update Screenshots
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Update Screenshots
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup host
        uses: ./.github/actions/setup-host
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github.actions@users.noreply.github.com"
      - name: Update Screenshots
        uses: ./.github/actions/start-emulator
        with:
          script: ./gradlew updateScreenshotTest recordDebugAndroidTestScreenshots
      - name: Commit updated screenshots
        run: |
          git add '**/src/*/screenshotTest/**' '**/src/androidTest/screenshot/**'
          git commit -m "Updated screenshots"
          git push origin
