name: Update Screenshots
on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
  workflow_dispatch:

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    name: Update Screenshots
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'update screenshots') }}
    uses: ./.github/workflows/ui-tests.yaml
    secrets: inherit
    with:
        update-screenshots: true
